
// This file is automatically generated. Do not modify it manually.

/**
 * The Firebase configuration object.
 */
export const firebaseConfig = {
  "projectId": "studio-8884276633-9c752",
  "appId": "1:68023693802:web:2cf701242560c3b10d4293",
  "apiKey": "AIzaSyC8uUCfDUIz7u-2xrGuTQmMq5TR_KtnarI",
  "authDomain": "studio-8884276633-9c752.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "68023693802"
};

/**
 * The database URL for the Firebase project.
 */
export const databaseURL = "https://studio-8884276633-9c752.firebaseio.com";
